sudo: false
language: python
python:
  - 2.7
  - 3.5

install: pip install tox-travis
script: tox

deploy:
  # deploy to PyPI on tags
  - provider: pypi
    server: https://upload.pypi.org/legacy/
    on:
      repo: anthrotype/extractor
      tags: true
      all_branches: true
      python: 3.5
    user: anthrotype
    password:
      secure: XXQ+GidvQPcLKMJ1FegFpLn6lYn3px/+TPwbHrRZKwLyec7WjFnqkt11IFyQeK0kWuqOzkeozkb5okGwb461pHNTv7PkuwoWhpOZeoYQ8j1tyTv0ALoExqksrJvA6xkC4bRhnBoLuCTMZxu2h998OeRINw2ILGDlXtFp7ebnyqY=
    distributions: sdist bdist_wheel
  # also create a Github Release with current tag
  - provider: releases
    api_key:
      secure: IiuH56pXP32TOSpdKvh6D82uhWyhyU+5VVYBiyygDIQi5N+PsaHjGt6Ei7HyKjRbHceBJhYG+ZnSFrBskCgVIODGRThYD99Q5bXJAG8F1nfHJlvsdfhX5NK6cOm2mX2djtROydgTyEgXfVIGVQJ8C1Cz8Hz3XDNqE8F50YuYsfM=
    file_glob: true
    file: "dist/*"
    skip_cleanup: true
    on:
      repo: anthrotype/extractor
      tags: true
      all_branches: true
      python: 3.5
