sudo: false
language: python
python:
  - 2.7
  - 3.5

install: pip install tox-travis
script: tox

deploy:
  # deploy to PyPI on tags
  - provider: pypi
    server: https://upload.pypi.org/legacy/
    on:
      repo: anthrotype/extractor
      tags: true
      all_branches: true
      python: 3.5
    user: anthrotype
    password:
      secure: j80CZr2m3srL2ZiIyXGQNx/od1zywo4O7nXg8PX4qKDmPX2CdMZW8b5ZkGZWRrLN2g/Ssd6Qo0WRQTkniz6/SDiBj4x9CJWJ+UbzIsJyAEEgiqF76Tp/kz0HESzJROwfuo67PX3bafyGWvBjDA9cS6xyp2j4rklq6+swCkbDk7NLmFqUps8XE1x4LIJFiF/hkDXxBvjXkitCHA9Z5NPViURujYLyWJ2mRBkWwyRN9q8xkH1pzo4OLuoblxi3u1kWhfcnJmZ3EX24g47oRqCPnChYKk4aArcoGPiRVclB7Ma6zE/fBtjqeMmaDmQw0g6HBFKLhJBXDc4hn8DNP6oGAtPi1FkKuG84CV/KwGGJ4/sulyuZj+73uZ8Hkr9hhEQBcqwWsyrYdzvQPUf1hdgScmGFnhdqubOY5+XOTGq5Jk1NvPg6K+yI9e6FxfWCWOD8Hzv4kz/qsbZ6JIEzb0c7EFnnRQFsTNbtB9ChJJol5dZCP7g5eQ+mZZVzxQ/l4VpZT7hdkb0UjBrk+eIJRgQGOIFM435Ul9bwp1ALddvnhytx++daFtk1/+6cd3kDbaeF+cHNkCsshfQE1O2E+GbEI+Ddm24Sw6dd2g6RbH4bBLdElFhMDx82SxgfNx7Jtx9NhNzqnOP9Xx+1NRRN1RXkxz9DFrs/KbNJOzv+qRk5ZP0=
    distributions: sdist bdist_wheel
  # also create a Github Release with current tag
  - provider: releases
    api_key:
      secure: IiuH56pXP32TOSpdKvh6D82uhWyhyU+5VVYBiyygDIQi5N+PsaHjGt6Ei7HyKjRbHceBJhYG+ZnSFrBskCgVIODGRThYD99Q5bXJAG8F1nfHJlvsdfhX5NK6cOm2mX2djtROydgTyEgXfVIGVQJ8C1Cz8Hz3XDNqE8F50YuYsfM=
    file_glob: true
    file: "dist/*"
    skip_cleanup: true
    on:
      repo: anthrotype/extractor
      tags: true
      all_branches: true
      python: 3.5
